# Site settings
title: 此间·我们
email: im@cijian.us
description: 缅怀那些我们在一起的日子~
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://192.168.33.10:4000" # the base hostname & protocol for your site
twitter_username: MurphyLuo
github_username:  MurphyL

# Build settings
markdown: kramdown

author: MurphyL
favico: /assets/img/icon.png
color: "#E0EBE8"
