# Site settings
title: 此间·我们
description: 缅怀那些我们在一起的日子~
keywords: "诗歌, 回忆, JavaScript, Node, CSS, HTML, HTML5, PDF, PPT, design, ued"
url: "http://cijian.us"
baseurl: ""
paginate: 10

permalink: "/:title"
paginate_path: "/page/:num"

author:
    name: MurphyL
    email: im@cijian.us
    weibo: MurphyLuo
    github: MurphyL
    twitter: MurphyLuo

gems: [jekyll-paginate]

sass:
    style: compressed

markdown: kramdown

kramdown:
    input:          GFM
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   "lsquo,rsquo,ldquo,rdquo"
    enable_coderay: false

coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style


