# Site settings
title: 此间·我们
email: im@cijian.us
description: 缅怀那些我们在一起的日子~
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10
url: "http://cijian.us"
permalink: "/:title"
paginate_path: "/page/:num"
author: MurphyL
twitter_username: MurphyLuo
github_username:  MurphyL

favico: /assets/img/icon.png
color: "#E0EBE8"

# Build settings
markdown: kramdown
kramdown:
  input:    GFM
  auto_ids: true
  syntax_highlighter: rouge
