auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 此间我们
description: 养心如葵，素心如兰
author: MurphyL
url: http://pale.cijian.us/
favico: /assets/img/icon.png
color: "#E0EBE8"
twitter: @MurphyLuo
feed: /atom.xml
