# Site settings
title: 此间·我们
email: im@cijian.us
description: 缅怀那些我们在一起的日子~
keywords: "诗歌, 回忆, JavaScript, Node, CSS, HTML, HTML5, PDF, PPT, design, ued"
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 10
url: "http://cijian.us"
permalink: "/:title"
paginate_path: "/page/:num"

author:
    name: MurphyL
    email: im@murphyl.com
    weibo: MurphyLuo
    github: MurphyL
    twitter: MurphyLuo

favico: /assets/img/icon.png
color: "#E0EBE8"

markdown: kramdown

kramdown:
    input:          GFM
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   "lsquo,rsquo,ldquo,rdquo"
    enable_coderay: false

coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style


